N=2000;
NA=0.5;
T_um=0.234;
z1_um=5;
z2_um=20000;
lambda_um=13.5e-3;
dDetectorSize=26;
halfD=dDetectorSize/2*1e3;
xIdx        = linspace(-halfD, halfD, N);
yIdx        = linspace(-halfD, halfD, N);
NAs=NA*halfD/(tan(asin(NA))*z2_um);
[X, Y]      = meshgrid(xIdx,yIdx);
xIdxs        = z2_um*tan(asin(NAs*linspace(-1, 1, N)));
yIdxs        = z2_um*tan(asin(NAs*linspace(-1, 1, N)));
[Xs, Ys]      = meshgrid(xIdxs,yIdxs);
[pxs,pys]=meshgrid(NAs*linspace(-1, 1, N));
px=sin(atan(X/z2_um));
py=sin(atan(Y/z2_um));
thita=6;
offset=z1_um*tan(thita/180*pi);
Xc=X/z2_um*z1_um+offset;
Yc=Y/z2_um*z1_um;
%  E=4+exp(1i*2*pi*Xc/T_um)+exp(-1i*2*pi*Xc/T_um)+exp(1i*2*pi*Yc/T_um)+exp(-1i*2*pi*Yc/T_um);
  E=exp(1i*2*pi*Xc/lambda_um*sin(thita/180*pi))+exp(1i*2*pi*sqrt(Xc.^2+Yc.^2+z1_um.^2)/lambda_um);
% E=4+exp(1i*2*pi*Xc/T_um+2*1i*2*pi*Yc/T_um)+exp(1i*2*pi*Xc/T_um-2*1i*2*pi*Yc/T_um)+exp(-1i*2*pi*Xc/T_um+2*1i*2*pi*Yc/T_um)+exp(-1i*2*pi*Xc/T_um-2*1i*2*pi*Yc/T_um);
I=abs(E).^2;
th=2;
I(I<th)=0;
I(I>th)=1;
figure(1),imshow(I,[])
% figure(1),mesh(X,Y,I); axis tight equal;
 figure(2),mesh(abs(fftshift(fft2(I))));